<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Révisions" data-toc-modified-id="Révisions-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Révisions</a></span></li><li><span><a href="#Test-d'adéquation-du-$\chi^2$" data-toc-modified-id="Test-d'adéquation-du-$\chi^2$-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Test d'adéquation du $\chi^2$</a></span></li><li><span><a href="#Test-d'indépendance-du-$\chi^2$" data-toc-modified-id="Test-d'indépendance-du-$\chi^2$-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Test d'indépendance du $\chi^2$</a></span></li><li><span><a href="#Assimiliation" data-toc-modified-id="Assimiliation-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Assimiliation</a></span></li><li><span><a href="#Test-d'homogénéité-du-$\chi^2$" data-toc-modified-id="Test-d'homogénéité-du-$\chi^2$-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Test d'homogénéité du $\chi^2$</a></span></li><li><span><a href="#Test-d'adéquation-de-Kolmogorov-Smirnov" data-toc-modified-id="Test-d'adéquation-de-Kolmogorov-Smirnov-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Test d'adéquation de Kolmogorov-Smirnov</a></span></li><li><span><a href="#Synthèse---Conclusions-(facultatif)" data-toc-modified-id="Synthèse---Conclusions-(facultatif)-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Synthèse - Conclusions (facultatif)</a></span></li></ul></div>

Tests non-paramétriques
============

# Préliminaires

Importez le jeu de données "iris_data.csv".

Présentation :

1. sepal length in cm
2. sepal width in cm
3. petal length in cm
4. petal width in cm
5. class: Iris-setosa, Iris-versicolor, Iris-virginica.

Faites en sorte de pouvoir acceder facilement aux différents attributs, par catégorie ou globalement.
Par exemple, vous pouvez faire trois tableaux "versicolor","virginica","setosa" contenant chacun les données numériques des iris de la variété.

In [11]:
import numpy as np

file = open("iris_data.csv","r")
setosa = np.array([])
virginica = np.array([])
versicolor = np.array([])
for line in file:
    liste = line.split(',')
    iris_num = np.array(liste[0:4],dtype=float)
    iris_name = np.array(liste[4],dtype='U')
    if iris_name == "Iris-setosa\n":
        setosa = np.concatenate((setosa,iris_num))
    if iris_name == "Iris-virginica\n":
        virginica = np.concatenate((virginica,iris_num))
    if iris_name == "Iris-versicolor\n":
        versicolor = np.concatenate((versicolor,iris_num))
setosa = np.reshape(setosa,(-1,4))
versicolor = np.reshape(versicolor,(-1,4))
virginica = np.reshape(virginica,(-1,4))
file.close()

# TP 4 : Adéquation et indépendance

## Révisions

Effectuez les calculs suivant :

+ La moyenne et l'écart-type de la longueur des sépales, toute catégorie confondue, puis uniquement pour la variété "virginica"
+ La moyenne et l'écart-type de la longueur des pétales, pour les variétés "setosa" et "versicolor"

In [12]:
tous = np.concatenate((setosa, versicolor, virginica))
# La moyenne et l'écart type de la longueur des sépales de tous
sepale_avg = np.mean(tous[:,0]);
sepale_std = np.std(tous[:,0]);
nobs_tous = tous.shape[0];
print("La moyenne de la longueur des sépales de toutes", nobs_tous, " fleures est de", sepale_avg, "cm")
print("L'écart-type de la longueur des sépales de toutes", nobs_tous, " fleures est de", sepale_std, "cm")

# La moyenne et l'écart-type de la longueur des sépales de virginica
sepale_virginica_avg = np.mean(virginica[:,0])
sepale_virginica_std = np.std(virginica[:,0])
nobs_virginica = virginica.shape[0]
print("La moyenne de la longueur des sépales des", nobs_virginica, "virginicas est de", sepale_virginica_avg, "cm")
print("L'écart-type de la longueur des sépales des", nobs_virginica, "virginicas est de", sepale_virginica_std, "cm")


# La moyenne et l'écart-type de la longueur des pétales des setosa
petale_setosa_avg = np.mean(setosa[:,0]);
petale_setosa_std = np.std(setosa[:,0]);
nobs_setosa = setosa.shape[0]
print("La moyenne de la longueur des pétales des", nobs_setosa, "setosa est de", petale_setosa_avg, "cm")
print("L'écart-type de la longueur des pétales des", nobs_setosa, "setosa est de", petale_setosa_std, "cm")

# La moyenne et l'écart-type de la longueur des pétales des versicolor
petale_versicolor_avg = np.mean(versicolor[:,0]);
petale_versicolor_std = np.std(versicolor[:,0]);
nobs_versicolor = versicolor.shape[0]
print("La moyenne de la longueur des pétales des", nobs_versicolor, "versicolor est de", petale_versicolor_avg, "cm")
print("L'écart-type de la longueur des pétales des", nobs_versicolor, "versicolor est de", petale_versicolor_std, "cm")

La moyenne de la longueur des sépales de toutes 150  fleures est de 5.843333333333334 cm
L'écart-type de la longueur des sépales de toutes 150  fleures est de 0.8253012917851409 cm
La moyenne de la longueur des sépales des 50 virginicas est de 6.587999999999998 cm
L'écart-type de la longueur des sépales des 50 virginicas est de 0.6294886813914926 cm
La moyenne de la longueur des pétales des 50 setosa est de 5.006 cm
L'écart-type de la longueur des pétales des 50 setosa est de 0.3489469873777391 cm
La moyenne de la longueur des pétales des 50 versicolor est de 5.936 cm
L'écart-type de la longueur des pétales des 50 versicolor est de 0.5109833656783751 cm


On fait l'hypothèse de normalité pour les grandeurs étudiées, par catégorie et globalement.

+ Testez l'égalité de longueur des pétales pour les deux variétés au seuil de $5\%$
+ La variété "virginica" a-t-elle une longueur de sépales significativement différente au sein de l'espèce ?

In [13]:
from scipy import stats as st

# Testez l'égalité de longueur des pétales pour les deux variétés au seuil de 5%
ttest = st.ttest_ind(versicolor[:, 2], setosa[:, 2]);
t_H0 = (ttest.pvalue >= 0.05);
print("• On accepte l'hypothèse que les deux variétés ont la même longueur de pétale à 5%") if t_H0 else print("• On rejette l'hypothèse que les deux variétés ont la même longueur de pétale à 5%")

# La variété "virginica" a-t-elle une longueur de sépales significativement différente au sein de l'espèce ?

# On suppose que l'écart-type de l'espèce est 0.82
# Test de conformité sur la variance

ktest2 = (nobs_virginica - 1)*(sepale_virginica_std**2)/(sepale_std**2)
k_pvalue = st.chi2.sf(ktest2, nobs_virginica - 1);
k_H0 = k_pvalue > 0.05; 
print("• On accepte l'hypothèse que la variété virginica ait une longueur de sépales significativement différente au sein de l'espèce à 5%") if k_H0 else print("• On rejette l'hypothèse que la variété virginica ait une longueur de sépales significativement différente au sein de l'espèce à 5%")



• On rejette l'hypothèse que les deux variétés ont la même longueur de pétale à 5%
• On accepte l'hypothèse que la variété virginica ait une longueur de sépales significativement différente au sein de l'espèce à 5%


## Test d'adéquation du $\chi^2$

*Prononcez "qi-deux" ou à la belge "qi-carré"*

Suivant la vitesse à laquelle vous avancez :

+ Lentement : testez la normalité de la longueur des sépales globalement, puis la longueur des pétales pour les "setosa"
+ Rapidement : testez la normalité des quatres attributs pour les trois variétés et globalement

** Le test du $\chi^2$ requiert des catégories, vous devez les créer vous-même **

In [14]:
# Fonction pour diviser une list en categories-effectifs 
from IPython.display import HTML, display

def evaluer(test):
    #print(test)
    return (test.pvalue > 0.05)

def afficherTable(string, data):
    """
        Synopsis: Afficher le contenu d'une table
            • data (array): la liste
            • string: le titre
    """
    print(string, '\n')
    display(HTML(
            '<table><tr>{}</tr></table>'.format(
            '</tr><tr>'.join(
                '<td>{}</td>'.format('</td><td>'.join(str(_) for _ in row)) for row in data)
            )
         ))

def categoriser(data, n, axis=None, output=1):
    """
        Synopsis: Categoriser une liste 'data' en 'n' catégories équiprobables (1/n), selon un 'axis'
        Parametres: 
            • data (array): la liste à catégoriser
            • axis (int): None - la liste sera traitée comme un tableau 1D 
            • output (0, 1, 2): 0 - retourner le couple histogram/bins 1 - histogram 2- bins
        Return: [historgram, edges] où histogram est l'effectif de chaque catégorie et edges sont les sous intervalles
    """
    if axis==None :
        return  np.histogram(data, n) 
    else:
        len = np.shape(data)[axis]
        histograms, bins = np.histogram(data[:, 0], n)
        for i in range(1, len):
            hist, edges = np.histogram(data[:, i], n) #NumPy ez
            histograms = np.vstack((histograms, hist)) # Empiler les histogrammes, util pour faire les calculs avec les arrays
            bins = np.vstack((bins, edges))
            
    #afficherTable("Histogram: ", histograms)

    if output==0: return (histograms, bins)
    elif output == 1: return histograms
    else: return bins 
    
def expect_gof(data, bins, axis=0): 
    """
        Synopsis: Calculer les valeurs attendues en cas de test Chi-2 d'adéquation.
    """   
        
    shape = np.shape(bins)
    res = np.empty((shape[1]-1, ))
    
    for r in range (0, shape[0]):
        row = bins[r, :]
        rrow = []
        for c in range (1, row.size):
            mean = np.mean(row)
            std = np.std(row)
            c =  np.sum(data) * (st.norm.sf(row[c], mean, std) - st.norm.sf(row[c-1], mean, std))
            rrow = np.hstack((rrow, c))
        #print(rrow)
        res = np.vstack((res, rrow))
    return np.delete(res, 0, axis=0)

def chi2_test_manual(f_obs, f_exp, mode=0, ind_mode=None, df=1):
    
    """
    Synopsis: faire le test chisquare à la main
    + mode: 0 - adequation, 1 - independance
    + ind_mode: en cas d'independance, 1 si homogeneité
    """
    shape = np.shape(f_obs)

    stat = np.sum(np.power((f_obs-f_exp), 2)/f_exp)
    
    dl = df
    
    if mode == 1:
        dl = (shape[0] - 1) * (shape[1] - 1) if ind_mode==0 else shape[0]*shape[1]
                   
    pvalue = st.chi2.sf(stat, dl)    
    return stat, pvalue

def chi2_adequation_manual(f_obs, f_exp):
    
    stats = []
    pvalues = []
    
    for i in range(0, 4):
        obs = f_obs[:, i]
        exp = f_exp[:, i]
        stat, pvalue = chi2_test_manual(obs, exp, mode=0, df=f_obs.shape[1]-1)
        stats = np.hstack((stats, stat))
        pvalues = np.hstack((pvalues, pvalue))
    
    return stats, pvalues

# Le test avec n bins (n >= 5)
n_bins = 6

# Categoriser
virginica_observed, virginica_bins = categoriser(virginica, n_bins, axis=1, output=0)
setosa_observed, setosa_bins = categoriser(setosa, n_bins, axis=1, output=0)
versicolor_observed, versicolor_bins = categoriser(versicolor, n_bins, axis=1, output=0)
total_observed, total_bins = categoriser(tous, n_bins, axis=1, output=0)

# np.sum(f_observed, axis=1) = l'effectif total de la variété
virginica_expected = expect_gof(virginica_observed, virginica_bins, axis=0)
setosa_expected = expect_gof(setosa_observed, setosa_bins, axis=0)
versicolor_expected = expect_gof(versicolor_observed, versicolor_bins, axis=0)
total_expected = expect_gof(total_observed, total_bins, axis=0)

# H0: Les mesures de l'échantillon sont adéquates à la distribution de la population
# df = 2
# True: accepte H0 à 5%, False: rejetter H0 à 5%

print("H0: Les mesures de l'échantillon sont adéquates à la distribution normale")

print("[sepal_length, sepal width, petal_length, petal_width]")

virginica_ktest = st.chisquare(virginica_observed, virginica_expected, axis=1, ddof=3)
virginica_ktest2 = chi2_adequation_manual(virginica_observed, virginica_expected)
print("chi2_adequation_manual: ", virginica_ktest2[1] > 0.05)
print("st.chisquare virginica: ", evaluer(virginica_ktest))

setosa_ktest = st.chisquare(setosa_observed, setosa_expected, axis=1, ddof=3)
setosa_ktest2 = chi2_adequation_manual(setosa_observed, setosa_expected)
print("chi2_adequation_manual: ", setosa_ktest2[1] > 0.05)
print("st.chisquare setosa: ", evaluer(setosa_ktest))

versicolor_ktest = st.chisquare(versicolor_observed, versicolor_expected, axis=1, ddof=3)
versicolor_ktest2 = chi2_adequation_manual(versicolor_observed, versicolor_expected)
print("chi2_adequation_manual: ", versicolor_ktest2[1] > 0.05)
print("st.chisquare versicolor: ", evaluer(versicolor_ktest))

total_ktest = st.chisquare(total_observed, total_expected, axis=1, ddof=3)
total_ktest2 = chi2_adequation_manual(total_observed, total_expected)
print("chi2_adequation_manual: ", total_ktest2[1] > 0.05)
print("st.chisquare tous: ", evaluer(total_ktest))




H0: Les mesures de l'échantillon sont adéquates à la distribution normale
[sepal_length, sepal width, petal_length, petal_width]
chi2_adequation_manual:  [ True  True  True  True]
st.chisquare virginica:  [ True  True  True  True]
chi2_adequation_manual:  [ True  True  True  True]
st.chisquare setosa:  [ True  True  True  True]
chi2_adequation_manual:  [ True  True  True  True]
st.chisquare versicolor:  [ True  True  True  True]
chi2_adequation_manual:  [ True  True  True  True]
st.chisquare tous:  [ True  True  True  True]


## Test d'indépendance du $\chi^2$

Etudiez l'indépendance la longueur des sépales et des pétales :

+ Créez le tableau de contingence $2$ lignes x $2$ colonnes. Les deux lignes sont "sépales court" (critère : inférieur à la moyenne) et "sépales long" (les autres). En colonne, même idée pour les pétales. Remplissez le tableau avec les effectifs.

    • Exemple avec le tableau de contingence pour la variété SETOSA:
    
+ Calculez le tableau avec les effectifs théoriques attendus en cas d'indépendance
+ Concluez

In [15]:
def contingence_1set(data, attributes, mode="average", bins=None):
    """
    Synopsis: Creer la table contingence 
        + data: les donnéees
        + attibutes: les indices des attributs à étudier
    """
    
    set1 = data[:,attributes[0]]
    set2 = data[:,attributes[1]]
    
    s_min = np.min(set1)
    s_max = np.max(set1)
        
    p_min = np.min(set2)
    p_max = np.max(set2)
    
    s_bins = bins
    p_bins = [p_min, np.mean(set2), p_max]
        
    if(mode == "average"):
        s_bins = [s_min, np.mean(set1), s_max]
            
    elif(mode == "percentile"):
        s_bins = np.hstack((s_min, np.percentile(set1, (25, 50, 75)), s_max))
            
    else: 
        if(bins==None): return None
        
    c_hist, s_edges, p_edges = np.histogram2d(data[:, attributes[0]], data[:, attributes[1]], bins=(s_bins, p_bins));  
    # afficherTable((s_edges, p_edges), c_hist);
    return c_hist

def contingency_2sets(sets, attribut:int, mode=None, bins=None):
    """
    Synopsis: Creer la table contingence pour le test chi2
    - sets: 2 sets à tester
    - attribut: l'attribut concerné
    - mode: average ou percentile
    """
    
    set1 = sets[0] [:,attribut]
    set2 = sets[1] [:,attribut]
    
    s_min = np.min(set1)
    s_max = np.max(set1)
        
    p_min = np.min(set2)
    p_max = np.max(set2)
    
    s_bins = bins
    p_bins = [p_min, np.mean(set2), p_max]
        
    if(mode == "average"):
        s_bins = [s_min, np.mean(set1), s_max]
            
    elif(mode == "percentile"):
        s_bins = np.hstack((s_min, np.percentile(set1, (25, 50, 75)), s_max))
            
    else:
        if(bins == None): return None
        
    c_hist, s_edges, p_edges = np.histogram2d(set1, set2, bins=(s_bins, p_bins));    
    # afficherTable((s_edges, p_edges), c_hist);
    return c_hist

def chi2_expected(f_obs):
    
    f_exp = np.empty_like(f_obs)
    
    hv_sum = np.sum(f_obs);
    
    shape = np.shape(f_obs)
    for r in range(0, shape[0]):
        for c in range(0, shape[1]):
            h_sum = np.sum(f_obs[r, :])
            v_sum = np.sum(f_obs[:, c])
            f_exp[r][c] = h_sum*v_sum/hv_sum
    
    #print(f_exp)
    return f_exp

def chi2_contingence_manuel(data, test_mode, bin_mode="average", bins=None):
    """
    Synopsis: Faire à la main le test d'indépendance ou d'homogénéité
        + data: l'échantillon
        + test_mode: 0-independance, 1-homogeneite
        + bin_mode: "average" - "percentile" - None
    """
    
    stats = []
    pvalues = []
    
    if(test_mode==0):
        f_obs = contingence_1set(data, (0, 2), bin_mode, bins)
        f_exp = chi2_expected(f_obs)
        stats = np.sum(np.power((f_obs-f_exp), 2)/f_exp)
        shape = np.shape(f_obs)
        df = (shape[0] - 1) * (shape[1] - 1) if test_mode==0 else shape[0]*shape[1]
        pvalues = st.chi2.sf(stats, df)
        
    else:
        for attribut in range(0, 4):
            f_obs = contingency_2sets(data, attribut, bin_mode, bins)
            f_exp = chi2_expected(f_obs)
            
            stat, pvalue = chi2_test_manual(f_obs, f_exp, mode=1, ind_mode=test_mode)

            stats = np.hstack((stats, stat))
            pvalues = np.hstack((pvalues, pvalue))
        
    print("stats: ", stats)
    print("pvalues: ", pvalues)
        
    return (stats, pvalues)

In [16]:
c_observed = contingence_1set(tous, (0, 2), "average");
c_ktest = st.chi2_contingency(c_observed)
c_ktest2 = chi2_contingence_manuel(tous, test_mode=0, bin_mode="average")

print("[sepal_length, sepal width, petal_length, petal_width]")

print("pvalue en test manuel: ", c_ktest2[1])

print(c_ktest[1])
print("On accepte l'hypothese que la longueur des sépales et des pétales est indépendante à 5%") if (c_ktest[1] > 0.05) else print("On rejette l'hypothese que la longueur des sépales et des pétales est indépendante à 5%")

# H0: la longueur des sépales et des pétales est indépendante
# True: accepte H0 à 5%, False: rejetter H0 à 5%




stats:  80.4435483870968
pvalues:  2.991296292911805e-19
[sepal_length, sepal width, petal_length, petal_width]
pvalue en test manuel:  2.991296292911805e-19
1.362784516029828e-18
On rejette l'hypothese que la longueur des sépales et des pétales est indépendante à 5%


## Assimiliation

Dans le tableau précédent, remplacez les $2$ lignes par $4$ lignes où les catégories sont "inférieur à $Q_1$", "entre $Q_1$ et la médiane", "entre la médiane et $Q_3$" et "supérieur à $Q_3$" où $Q_1$ signifie premier quartile et $Q_3$ désigne $\ldots$ le troisième.

In [17]:
#H0: la longueur des sépales et des pétales est indépendante
# True: accepte H0 à 5%, False: rejetter H0 à 5%

q_observed = contingence_1set(setosa, (0, 2), "percentile");
q_ktest = st.chi2_contingency(q_observed)
q_ktest2 = chi2_contingence_manuel(setosa, test_mode=0, bin_mode="percentile")

print("[sepal_length, sepal width, petal_length, petal_width]")

print("pvalues en test manuel: ", q_ktest2[1])

print(q_ktest[1])
print("On accepte l'hypothese que la longueur des sépales et des pétales est indépendante à 5%") if (q_ktest[1] > 0.05) else print("On rejette l'hypothese que la longueur des sépales et des pétales est indépendante à 5%")

stats:  7.324277976451891
pvalues:  0.06224963044906766
[sepal_length, sepal width, petal_length, petal_width]
pvalues en test manuel:  0.06224963044906766
0.06224963044906766
On accepte l'hypothese que la longueur des sépales et des pétales est indépendante à 5%


# TP5 : Homogénéité et Adéquation

## Test d'homogénéité du $\chi^2$

Sur le modèle des tests d'indépendance du TP précédent (soit $2$ catégories avec la moyenne, soit $4$ catégories avec les quartiles), testez si l'un des attributs permet de conclure à une inhomogénéité entre les variétés "virginica" et "versicolor".

Vous pouvez faire un tableau de contingence avec $2$ colonnes ("virginica" et "versicolor") et $2$ ou $4$ lignes; remplissez avec les effectifs et $\ldots$ en avant Guimgamp !

V4
+ Vos deux populations : `versicolor` et `virginica`
+ Votre caractère : `sepal width` (colonne 2, indice 1)
+ Le minimum : $2.0$, le maximum : $3.8$
+ Vous faites $6$ catégories : $\lbrack 2.0,2.3 \rbrack$,$\lbrack 2.3,2.6 \rbrack$,
$\lbrack 2.6,2.9 \rbrack$,$\lbrack 2.9,3.2 \rbrack$,$\lbrack 3.2,3.5 \rbrack$,$\lbrack 3.5,3.8 \rbrack$
+ Vous calculez les effectifs *observés*, *théoriques*
+ Puis vous mettez en place votre test.

In [18]:
def chi2_contingency(sets, mode="average", bins=None):
    """
    Synopsis: Faire le test st.chi2_contingency pour les memes attributs des deux ensembles
    - sets: 2 sets à tester
    - mode: average ou percentile
    """
    res = []
    for attribut in range(0, 4):
        h_contingency = contingency_2sets(sets, attribut, mode, bins)
        h_qtest = st.chi2_contingency(h_contingency)
        res = np.hstack((res, h_qtest[1]))
    return res
        
print("H0: chaque variété iris a le meme proportion d'observations pour chaque attribut. True: accept à 5%")

h_bins = [2.0, 2.3, 2.6, 2.6, 2.9, 3.2, 3.5, 3.8]
h_qtests = chi2_contingency((virginica, versicolor), bins=h_bins)
h_qtests_avg = chi2_contingency((virginica, versicolor), "average")
h_qtests_percentile = chi2_contingency((virginica, versicolor), "percentile")

h_qtests2 = chi2_contingence_manuel((virginica, versicolor), test_mode=1)

print("[sepal_length, sepal width, petal_length, petal_width]")

print("Test manuel: ", h_qtests2[1] > 0.05)

print("Test avec bins: ", h_qtests > 0.05)
print("Test avec les moyennes: ", h_qtests_avg > 0.05)
print("Test avec les quartiles: ", h_qtests_percentile > 0.05)


H0: chaque variété iris a le meme proportion d'observations pour chaque attribut. True: accept à 5%
stats:  [0.7913961  0.01091994 0.72463768 0.25304808]
pvalues:  [0.9395978  0.99998515 0.9482562  0.99264   ]
[sepal_length, sepal width, petal_length, petal_width]
Test manuel:  [ True  True  True  True]
Test avec bins:  [ True  True  True  True]
Test avec les moyennes:  [ True  True  True  True]
Test avec les quartiles:  [ True  True  True  True]


## Test d'adéquation de Kolmogorov-Smirnov

Reprenez les tests d'adéquation du TP précédent mais avec le test de Kolmogorov-Smirnov. Comparez vos réponses.

In [19]:
def kstest(data):
    """
    Synopsis: Faire le test Kolmogorov-Smirnov sur chaque attribut simultanément
    """
    pvalues = []
    stats = []
    for attribut in range(0, 4):
        sample = data[:, attribut]
        test = st.kstest(sample, "norm", args = (np.mean(sample), np.std(sample)))
        pvalues = np.hstack((pvalues, test.pvalue))
        stats = np.hstack((stats, test.statistic))
        
    print(stats)
    return pvalues

print("H0: Les mesures de l'échantillon sont adéquates à la distribution normale")
print("[sepal_length, sepal width, petal_length, petal_width]")
ks_virginica = kstest(virginica)
print(ks_virginica > 0.05)

ks_setosa = kstest(setosa)
print(ks_setosa > 0.05)

ks_versicolor = kstest(versicolor)
print(ks_versicolor > 0.05)

ks_tous = kstest(tous)
print(ks_tous > 0.05)


H0: Les mesures de l'échantillon sont adéquates à la distribution normale
[sepal_length, sepal width, petal_length, petal_width]
[0.11558941 0.12754622 0.1159698  0.12321555]
[ True  True  True  True]
[0.11381791 0.11395056 0.15699544 0.34077461]
[ True  True  True False]
[0.09790719 0.12220365 0.11827503 0.14717096]
[ True  True  True  True]
[0.0894544  0.10305478 0.19913534 0.17314802]
[ True  True False False]


+ Reprenez votre tableau contenant les largeurs des sépales de la variété `versicolor` et ** ordonnez-le ** (`numpy.sort`).
+ Calculez la moyenne $m$ et l'écart-type $s$ de cet échantillon. Vous allez tester l'adéquation de votre échantillon à la loi normale de moyenne $m$ et d'écart-type $s$.
+ Transformez votre échantillon pour qu'il soit centré-réduit (sous l'hypothèse $H_0$), calculez le tableau des fréquences cumulées pour la loi normale.
+ Générez les tableaux des $\frac{i}{n}$ et $\frac{i-1}{n}$, puis calculez les écarts.
+ Déduisez-en la statistique du test (`numpy.max`) puis retrouvez cette statistique avec la fonction `kstest`.
+ Concluez.

In [20]:
def kolmogorov_smirnov(data):
    
    stats = []
    pvalues = []
    
    for attribute in range(0, 4):
        sortedData = np.sort(data[:, attribute])

        mean = np.mean(sortedData)
        std = np.std(sortedData)

        centercut = (sortedData - mean)/std
        
        nobs = centercut.size
        freqc = np.array([st.norm.cdf(centercut[i]) for i in range(0,nobs)])
        i_n = [i/nobs for i in range(1,nobs+1)]
        i_1_n = [(i-1)/nobs for i in range(1,nobs+1)]
        ecarts_i = np.abs(freqc - i_n) 
        ecarts_i_1 = np.abs(freqc - i_1_n)
        
        stat = np.max(np.concatenate((ecarts_i,ecarts_i_1)))
        
        pvalue = st.norm.sf(stat, mean, std)
        
        stats = np.hstack((stats, stat))
        pvalues = np.hstack((pvalues, pvalue))
        
    print(stats)
    
    return pvalues

print("H0: Les mesures de l'échantillon sont adéquates à la distribution normale")
print("[sepal_length, sepal width, petal_length, petal_width]")
ks_virginica2 = kolmogorov_smirnov(virginica)
print(ks_virginica2 > 0.05)

ks_setosa2 = kolmogorov_smirnov(setosa)
print(ks_setosa2 > 0.05)

ks_versicolor2 = kolmogorov_smirnov(versicolor)
print(ks_versicolor2 > 0.05)

ks_total2 = kolmogorov_smirnov(tous)
print(ks_total2 > 0.05)
        

H0: Les mesures de l'échantillon sont adéquates à la distribution normale
[sepal_length, sepal width, petal_length, petal_width]
[0.11558941 0.12754622 0.1159698  0.12321555]
[ True  True  True  True]
[0.11381791 0.11395056 0.15699544 0.34077461]
[ True  True  True  True]
[0.09790719 0.12220365 0.11827503 0.14717096]
[ True  True  True  True]
[0.0894544  0.10305478 0.19913534 0.17314802]
[ True  True  True  True]


## Synthèse - Conclusions (facultatif)

Reprenez toute l'étude précédente, à l'envers :

+ Testez la normalité de la largeur des pétales, globalement puis pour la variété "virginica". Comparez les résutalts du test du $\chi^2$ et du test de Kolmogorov-Smirnov
+ La largeur moyenne des pétales de "virginica" est-elle significativement différentes de celle de l'espèce ?
+ La largeur des pétales est-elle indépendante de leur longueur ?
+ Sur l'attribut largeur des sépales, peut-on conclure que les échantillons "setosa" et "versicolor" sont différent ?

Travail déjà réalisé

# Expression libre (facultatif)

Effectuez d'autres tests du même genre que les précédents